name: 'Deploy on Comment'

on:
  issue_comment:
    types: 
      - created

jobs:
  deploy:
    permissions:
      pull-requests: write
    name: A testing job to try writing a comment in response to a comment
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy' }}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      # create a comment to output info about the build
      - name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "I'm going to build and deploy this PR to npm! Stay tuned..."

      # - name: Run stencil dev release...
      #   uses: ./.github/workflows/release-dev.yml

      - name: Update comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          # need to get the build version in here somehow, out of the deploy action
          body: |
            I'm going to build and deploy this PR to npm! Stay tuned...

            This PR was published to version ! 🎉

            Install it here:

            ```sh
            npm install @stencil/core@VERSION
            ```
          edit-mode: replace
