name: 'Deploy on Comment'

on:
  issue_comment:
    types:
      - created

jobs:
  create-comment:
    outputs:
      comment-id: ${{ steps.comment.outputs.comment-id }}
    permissions:
      pull-requests: write
    name: Create a comment for reporting on the release
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/release-dev' }}
    steps:
      # Create a comment to output info about the build
      - name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "I'm going to build and deploy this PR to npm! Stay tuned..."

  release:
    name: Run the release
    uses: ./.github/workflows/release-dev.yml
    needs: [create-comment]

  update-comment:
    needs: [create-comment, release]
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          comment-id: ${{ needs.create-comment.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            I'm going to build and deploy this PR to npm! Stay tuned...

            This PR was published to version ${{ needs.release.outputs.dev-version }}! 🎉

            Install it here:

            ```sh
            npm install @stencil/core@${{ needs.release.outputs.dev-version }}
            ```
          edit-mode: replace
