name: 'Deploy on Comment'

on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    permissions:
      pull-requests: write
    name: Publish a dev build to npm based on a PR comment
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/release-dev' }}
    steps:
      - name: authorize
        uses: octokit/request-action@v2.1.9
        with:
          route: GET /orgs/:organisation/teams/:team/memberships/${{ github.event.comment.user.id }}
          team: stencil
          organisation: ionic-team
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # we need this action because the HEAD on an 'issue' event is normally
      # the HEAD of the main branch, not the PR. This relates to the way that
      # Github treats issues and PRs as the same thing in some ways.
      # See https://github.com/xt0rted/pull-request-comment-branch
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7 # v2.0.0
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      # Create a comment to output info about the build
      - name: Create comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "I'm going to build and deploy this PR to npm! Stay tuned..."

      - name: Run stencil dev release...
        id: release
        uses: ./.github/workflows/release-dev.yml

      - name: Update comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            I'm going to build and deploy this PR to npm! Stay tuned...

            This PR was published to version ${{ steps.release.outputs.dev-version }}! 🎉

            Install it here:

            ```sh
            npm install @stencil/core@${{ steps.release.outputs.dev-version }}
            ```
          edit-mode: replace

      # probably need to find a good way to report a failure here
