name: 'Stencil Dev Release'
# this is a dummy 'release' script for testing out this workflow

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      dev-version:
        description: The version that was just published to npm.
        value: ${{ jobs.get-dev-version.outputs.dev-version }}

jobs:
  get-dev-version:
    name: Get Dev Build Version
    # needs: [build_core]
    runs-on: ubuntu-22.04
    outputs:
      dev-version: ${{ steps.get-dev-version.outputs.DEV_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Version
        id: get-dev-version
        run: |
          # store a key/value pair in GITHUB_OUTPUT
          # e.g. "DEV_VERSION=3.0.1-dev.1677185104.7c87e34"
          echo "DEV_VERSION=TEST_VERSION_NUMBER" >> $GITHUB_OUTPUT

        shell: bash
